// Generated by CoffeeScript 1.10.0
(function() {
  var LevelStore, app, authCheck, express, metrics, session, user;

  express = require('express');

  metrics = require('./metrics');

  user = require('./user');

  app = express();

  app.set('port', 1889);

  app.set('views', __dirname + "/../views");

  app.set('view engine', 'jade');

  app.use('/', express["static"](__dirname + "/../public"));

  session = require('express-session');

  LevelStore = require('level-session-store')(session);

  app.use(require('body-parser')());

  app.use(session({
    secret: 'MyAppSecret',
    store: new LevelStore('./db/sessions'),
    resave: true,
    saveUninitialized: true
  }));

  authCheck = function(req, res, next) {
    if (req.session.loggedIn !== true) {
      return res.redirect('/login');
    } else {
      return next();
    }
  };

  app.get('/', authCheck, function(req, res) {
    return res.render('index', {
      name: req.session.username
    });
  });

  app.get('/addMetric', function(req, res) {
    return res.render('addMetric', {
      name: req.session.username
    });
  });

  app.post('/addMetric', function(req, res) {
    return metrics.saveNew(req.session.username, req.body.timestamp, req.body.value, function(err, data) {
      if (err) {
        throw error;
      } else {
        return res.redirect('/');
      }
    });
  });

  app.get('/metrics.json', function(req, res) {
    return metrics.get(req.session.username, function(err, data) {
      return res.status(200).json(data);
    });
  });

  app.get('/login', function(req, res) {
    return res.render('login');
  });

  app.get('/signup', function(req, res) {
    return res.render('signup');
  });

  app.post('/login', function(req, res) {
    return user.get(req.body.username, function(err, data) {
      if (err) {
        return next(err);
      }
      if (!(req.body.username === data.username && req.body.password === data.password)) {
        return res.redirect('/login');
      } else {
        req.session.loggedIn = true;
        req.session.username = data.username;
        return res.redirect('/');
      }
    });
  });

  app.post('/signup', function(req, res) {
    return user.save(req.body.username, req.body.password, req.body.name, req.body.email, function(err) {
      if (err) {
        res.redirect('/signup');
      }
      return res.redirect('/login');
    });
  });

  app.get('/logout', function(req, res) {
    delete req.session.loggedIn;
    delete req.session.username;
    return res.redirect('/login');
  });

  app.listen(app.get('port'), function() {
    return console.log("server listening on " + (app.get('port')));
  });

}).call(this);
