// Generated by CoffeeScript 1.10.0
(function() {
  var db;

  db = require('./db')(__dirname + "/../db/user");

  module.exports = {
    get: function(username, callback) {
      var rs, user;
      rs = db.createReadStream({
        gte: "user:" + username,
        lte: "user:" + username
      });
      user = null;
      rs.on('data', function(data) {
        var key, properties;
        key = data.key.split(":");
        properties = data.value.split(":");
        user = {
          username: key[1],
          password: properties[1],
          name: properties[2],
          email: properties[3]
        };
        return user;
      });
      rs.on('error', callback);
      return rs.on('close', function() {
        return callback(null, user);
      });
    },
    save: function(username, password, name, email, callback) {
      var ws;
      ws = db.createWriteStream();
      ws.on('error', callback);
      ws.on('close', callback);
      ws.write({
        key: "user:" + username,
        value: "user:" + password + ":" + name + ":" + email
      });
      return ws.end();
    },
    remove: function(username, callback) {
      var toDel;
      toDel = "user:" + username;
      return db.del(username, callback);
    }
  };

}).call(this);
